### ISSUE TITLE
Question about generating simullated data in work ELIC-Calib

### ISSUE THREAD

**Issue by Rick0514** [Unsigned-Long/Unsigned-Long#1]
Hi, Ulong2:
    What an impressive work. However, a few questions remain. I am very curious about how you generate the simulated data. I have attempted to make Lidar data on Gazebo, but it seems not so good as yours. Could you give me some hint on how you achieve this?

Best regards,
Rick.

**Comment by Unsigned-Long** [comment]
Since **sufficiently excited motion is required for accurate spatiotemporal calibration** in `ELIC-Calib`, we create a simulated scenario using `Blender` and the corresponding sufficiently excited trajectory. We have uploaded the Blender model file at (https://drive.google.com/drive/folders/1UFkkEsjLAFdLWMdrD2K01fIfAk86xMMs?usp=sharing), you can download such file and create your simulated rosbag :ok_hand: .

**Comment by Rick0514** [comment]
> Since **sufficiently excited motion is required for accurate spatiotemporal calibration** in `ELIC-Calib`, we create a simulated scenario using `Blender` and the corresponding sufficiently excited trajectory. We have uploaded the Blender model file at (https://drive.google.com/drive/folders/1UFkkEsjLAFdLWMdrD2K01fIfAk86xMMs?usp=sharing), you can download such file and create your simulated rosbag 👌 .

Thanks for your quick reply and the share of  Blender model. Could you be so kind to elaborate on how to simulate point clouds from a LiDAR sensor under such model? I'd like to gain a deeper understanding of this process.

**Comment by Unsigned-Long** [comment]
import the blender model to the gazebo, create an actor whose trajectory is the same as the designed trajectory and install sensors on this actor, finally record data as rosbag.

Attention: such simulation would lead to the lack of inertial data, even if inertial measurement units are installed on this actor, as **an actor in the gazebo is not kinematic-drived**. Therefore, after data are recorded, you have to simulate IMU data using the prior trajectory (using continuous-time trajectories fitting, we have to admit this is a complicated process).

**Comment by Unsigned-Long** [comment]
Actually, the current `ELIC-Calib` is an old version. several months later, we would open-source a unified targetless spatiotemporal calibrator for integrated inertial systems resiliently integrating multiple heterogeneous sensors, e.g., multiple LiDARs, IMUs, Cameras, and Radars (note that resilience calibration is supported, e.g., the number of sensors, the type of sensors) :smile:. You can pay some attention to it when the time comes.

**Comment by Rick0514** [comment]
> import the blender model to the gazebo, create an actor whose trajectory is the same as the designed trajectory and install sensors on this actor, finally record data as rosbag.
> 
> Attention: such simulation would lead to the lack of inertial data, even if inertial measurement units are installed on this actor, as **an actor in the gazebo is not kinematic-drived**. Therefore, after data are recorded, you have to simulate IMU data using the prior trajectory (using continuous-time trajectories fitting, we have to admit this is a complicated process).

All my questions have been resolved thank to your enlightment!!! I'll have a try as you said. Wish you a good day.
